#!/bin/bash

clear
echo "Welcome to the Post Installation Setup by Murilo Varela"
echo ""
echo "First we need to update and upgrade"
#apt-get -qq update && sudo apt-get -qq upgrade -y

sudo apt-get -qq install whiptail -y
clear

cmd=(
  whiptail
    --title "Instalation Checklist" \
    --checklist \
    "Select what you want to be installed" \
    --separate-output \
  22 76 16
)

options=(
  1 "Google Chrome" on
  2 "Spotfy" on
  3 "Postman" on
  4 "Discord" on
  5 "Node Version Manager" on
  6 "Atom" on
  7 "Java Development Kit" on
  8 "Android SDK" on
  9 "Create React App" on
  10 "React Native" on
  11 "Reactotron" on
  12 "Unity Tweak Tool" on
  13 "Plank Docker" on
  14 "Arc Theme" on
  15 "Ruby" on
  16 "Zsh" on
)

selection=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
clear

counter=0
operations=($selection)
totalOperations=${#operations[@]}
for choice in $selection
do
  counter=$[counter + 1]

  case $choice in
    1)
      echo "Installing Google Chrome (${counter}/${totalOperations})"

      wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
      echo deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main | sudo tee /etc/apt/sources.list.d/google-chrome.list
      apt-get update -y
      apt-get install google-chrome-stable -y
    ;;

    2)
      echo "Installing Spotfy (${counter}/${totalOperations})"

      sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 0DF731E45CE24F27EEEB1450EFDC8610341D9410
      echo deb http://repository.spotify.com stable non-free | sudo tee /etc/apt/sources.list.d/spotify.list
      sudo apt-get update -y
      sudo apt-get install spotify-client -y
    ;;

    3)
      echo "Installing Postman (${counter}/${totalOperations})"

      wget https://dl.pstmn.io/download/latest/linux64 -O postman.tar.gz
      sudo tar -xzf postman.tar.gz -C /opt
      rm postman.tar.gz
      sudo ln -s /opt/Postman/Postman /usr/bin/postman
    ;;

    4)
      echo "Installing Discord (${counter}/${totalOperations})"

      sudo apt install libgconf-2-4 libappindicator1 -y
      wget "https://discordapp.com/api/download?platform=linux&format=deb" -O discord.deb
      sudo dpkg -i discord.deb
      rm discord.deb
    ;;

    5)
      echo "Installing Node Version Manager (${counter}/${totalOperations})"

      sudo -k
      wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
    ;;

    6)
      echo "Installing Atom (${counter}/${totalOperations})"

      sudo add-apt-repository ppa:webupd8team/atom -y
      sudo apt-get update -y
      sudo apt-get install atom -y

      apm install atom-beautify
      apm install atom-react-native-style
      apm install autocomplete-modules
      apm install file-icons
      apm install git-plus
      apm install highlight-selected
      apm install js-hyperclick
      apm install language-babel
      apm install linter
      apm install linter-eslint
      apm install linter-ui-default
      apm install merge-conflicts
      apm install nuclide
      apm install pigments
      apm install react-redux-atom-snippets
      apm install tab-foldername-index
      apm install tree-view-copy-relative-path
    ;;

    7)
      echo "Installing Java Development Kit (${counter}/${totalOperations})"

      sudo apt-get install openjdk-8-jdk -y
      apt-cache search jdk
      echo "export JAVA_HOME=/usr/lib/jvm/java-8-openjdk" >> ~/.bashrc
      echo "export PATH=$JAVA_HOME/bin" >> ~/.bashrc
    ;;

    8)
      echo "Installing Android SDK (${counter}/${totalOperations})"

      sudo apt-get install unzip -y
      wget https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip -O sdk-tools-linux.zip
      unzip sdk-tools-linux.zip -d ~/android
      echo "export ANDROID_HOME=~/android" >> ~/.bashrc
      echo "export PATH=$ANDROID_HOME/tools" >> ~/.bashrc
      echo "export PATH=$ANDROID_HOME/platforms" >> ~/.bashrc

      sudo -k
      wget https://raw.githubusercontent.com/murilovarela/avd-helper/master/avd-helper -O avd-helper
      chmod +x avd-helper
      mkdir ~/bin
      mv avd-helper ~/bin
      echo "export SCRIPTS_HOME=~/bin" >> ~/.bashrc
    ;;

    9)
      echo "Installing Create React App (${counter}/${totalOperations})"

      sudo -k
      npm install -g create-react-app
    ;;

    10)
      echo "Installing React Native (${counter}/${totalOperations})"

      sudo -k
      npm install -g react-native-cli
    ;;

    11)
      echo "Installing Reactotron (${counter}/${totalOperations})"

      sudo -k
      wget https://github.com/infinitered/reactotron/releases/download/v1.14.0/Reactotron-linux-x64.zip -O Reactotron-linux-x64.zip
      unzip Reactotron-linux-x64.zip -d ~/reactotron
      echo "export REACTOTRON_HOME=~/reactotron" >> ~/.bashrc
      echo "export PATH=$PATH:$REACTOTRON_HOME/Reactotron" >> ~/.bashrc
      npm install -g reactotron-cli
    ;;

    12)
      echo "Installing Unity Tweak Tool (${counter}/${totalOperations})"

      sudo apt-get install unity-tweak-tool -y
    ;;

    13)
      echo "Installing Plank Docker (${counter}/${totalOperations})"

      sudo add-apt-repository -y ppa:ricotz/docky
      sudo apt-get update -y
      sudo apt-get install plank -y
    ;;

    14)
      echo "Installing Plank Docker (${counter}/${totalOperations})"

      sudo add-apt-repository ppa:noobslab/themes
      sudo add-apt-repository ppa:noobslab/icons
      sudo apt-get update -y
      sudo apt-get install arc-theme arc-icons -y
    ;;

    15)
      echo "Installing Ruby (${counter}/${totalOperations})"

      sudo -k
      apt install ruby-full -y
    ;;

    16)
      echo "Installing Zsh (${counter}/${totalOperations})"

      sudo -k
      apt-get install zsh
      wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh
      chsh -s `which zsh`

      echo "export REACTOTRON_HOME=~/reactotron" >> ~/.zshrc
      echo "export PATH=$PATH:$REACTOTRON_HOME/Reactotron" >> ~/.zshrc
      echo "export ANDROID_HOME=~/android" >> ~/.zshrc
      echo "export PATH=$PATH:$ANDROID_HOME/tools" >> ~/.zshrc
      echo "export PATH=$PATH:$ANDROID_HOME/platforms" >> ~/.zshrc
      echo "export JAVA_HOME=/usr/lib/jvm/java-8-openjdk" >> ~/.zshrc
      echo "export PATH=$PATH:$JAVA_HOME/bin" >> ~/.zshrc
      echo "export NVM_DIR=$HOME/.nvm
      [ -s $NVM_DIR/nvm.sh ] && . $NVM_DIR/nvm.sh"
      echo "export SCRIPTS_HOME=~/bin" >> ~/.zshrc
      echo "ZSH_THEME="amuse"" >> ~/.zshrc
    ;;

  esac
done
